version: '3.8'
services:
  main-db:
    image: postgres:13
    container_name: freelance-app
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp

networks:
  freecodecamp: